
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const CREATE_HISTORY = 'CREATE_HISTORY'
export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PATIENTS_BY_ID = 'GET_PATIENTS_BY_ID';
export const DELETE_PATIENT  = 'DELETE_PATIENT';
export const SET_ERROR = 'SET_ERROR';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const GET_HISTORY = 'GET_HISTORY'
export const GET_OWN_PATIENTS = 'GET_OWN_PATIENTS';
export const NUMBER_OF_MEDICATION = 'NUMBER_OF_MEDICATION';
export const ENTER_MEDICATION = 'ENTER_MEDICATION';
export const NEW_HISTORY_ERROR ='NEW_HISTORY_ERROR'